[tool.poetry]
name = "backend"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8,<3.9"
aiohttp = "3.10.11"
aioredis = "1.3.1"
aiosignal = "1.3.1"
amqp = "5.1.1"
anyio = "3.7.1"
arrow = "1.2.3"
asgiref = "3.7.2"
async-timeout = "4.0.3"
attrs = "23.1.0"
autobahn = "23.1.2"
automat = "22.10.0"
backoff = "2.2.1"
backports-zoneinfo = "0.2.1"
beautifulsoup4 = "4.12.2"
billiard = "3.6.4.0"
bson = "0.5.10"
celery = "5.2.4"
certifi = "2023.7.22"
cffi = "1.15.1"
channels = "3.0.5"
channels-redis = "3.3.1"
charset-normalizer = "3.2.0"
click = "8.1.6"
click-didyoumean = "0.3.0"
click-plugins = "1.1.1"
click-repl = "0.3.0"
constantly = "15.1.0"
cryptography = "41.0.3"
cssutils = "2.7.1"
daphne = "3.0.2"
deprecated = "1.2.14"
django = "3.2.20"
django-celery-beat = "2.2.1"
django-inlinecss = "0.3.0"
django-json-widget = "1.1.1"
django-timezone-field = "4.2.3"
exceptiongroup = "1.1.2"
fqdn = "1.5.1"
frozenlist = "1.4.0"
future = "0.18.3"
googleapis-common-protos = "1.60.0"
graphql-core = "3.2.3"
grpcio = "1.57.0"
gunicorn = "20.1.0"
h11 = "0.14.0"
hiredis = "2.2.3"
hyperlink = "21.0.0"
idna = "3.4"
importlib-metadata = "6.8.0"
importlib-resources = "6.0.1"
incremental = "22.10.0"
isoduration = "20.11.0"
jsonpointer = "2.4"
jsonref = "0.3.0"
jsonschema = "4.4.0"
kombu = "5.3.1"
lxml = "4.9.2"
msgpack = "1.0.5"
multidict = "6.0.4"
notifiers = "1.3.3"
opentelemetry-api = "1.19.0"
opentelemetry-exporter-otlp = "1.19.0"
opentelemetry-exporter-otlp-proto-common = "1.19.0"
opentelemetry-exporter-otlp-proto-grpc = "1.19.0"
opentelemetry-exporter-otlp-proto-http = "1.19.0"
opentelemetry-proto = "1.19.0"
opentelemetry-sdk = "1.19.0"
opentelemetry-semantic-conventions = "0.40b0"
pika = "1.3.2"
pillow = "9.0.1"
promise = "2.3"
prompt-toolkit = "3.0.39"
protobuf = "4.24.0"
psycopg2-binary = "2.9.7"
pyasn1 = "0.5.0"
pyasn1-modules = "0.3.0"
pycparser = "2.21"
pygments = "2.16.1"
pyjwt = "2.7.0"
pynliner = "0.8.0"
pyopenssl = "23.2.0"
pyrsistent = "0.19.3"
python-crontab = "3.0.0"
python-dateutil = "2.8.2"
python-memcached = "1.59"
python-multipart = "0.0.5"
pytz = "2023.3"
requests = "2.31.0"
rfc3339-validator = "0.1.4"
rfc3986-validator = "0.1.1"
service-identity = "23.1.0"
six = "1.16.0"
sniffio = "1.3.0"
soupsieve = "2.4.1"
sqlparse = "0.4.4"
starlette = "0.31.0"
strawberry-graphql = "0.127.4"
strawberry-graphql-django = "0.4.0"
twisted = "22.10.0"
txaio = "23.1.1"
typing-extensions = "4.8.0"
tzdata = "2023.3"
uri-template = "1.3.0"
urllib3 = "1.26.16"
uvicorn = "0.18.3"
vine = "5.0.0"
wcwidth = "0.2.6"
webcolors = "1.13"
wrapt = "1.15.0"
zipp = "3.16.2"
zope-interface = "6.0"
faststream = "^0.4.7"
aio-pika = "^9.4.1"
cachetools = "5.5.2"
ratelimit = "^2.2.1"


[tool.poetry.group.dev.dependencies]
flake8 = "4.0.1"
coverage = "^7.3.2"
freezegun = "1.2.1"
django-stubs = "^4.2.7"
mypy = "^1.9.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
