"""
Django settings for main project.

Generated by 'django-admin startproject' using Django 3.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import base64
import os
import json
from datetime import datetime
from enum import Enum
from pathlib import Path
from datetime import timedelta
from dateutil.relativedelta import relativedelta
from plib.tracing import set_tracing_flag

# Build paths inside the project like this: BASE_DIR / 'subdir'.
from urllib.parse import quote

import pytz


def resolve_strange_bool(env_name):  # only for backward compatibility
    e = os.environ.get(env_name, False)
    if type(e) is str:
        if e in ['false', 'False', '', ' ']:
            return False
        elif e in ['true', 'True']:
            return True
    return bool(int(e))


BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'dev-only-change-me')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = json.loads(os.environ.get('DEBUG', "False").lower())

ALLOWED_HOSTS = ['*']

BASE_SITE_URL = os.environ.get('BASE_SITE_URL')

CSRF_TRUSTED_ORIGINS = [BASE_SITE_URL]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'strawberry.django',
    'django_celery_beat',
    'django_json_widget',
    'user_domain',
    'api_gateway',
    'collector_domain',
    'data_domain',
    'label_domain',
    'person_domain',
    'channels',
    'django_inlinecss',
]

APP_VERSION = os.environ.get('APP_VERSION')

# TRACING SETTINGS
SERVICE_NAME = f"backend-{APP_VERSION}"
TRACING_ENABLED = json.loads(os.environ.get('TRACING_ENABLED', "False").lower())
TRACER_HOST = os.environ.get('TRACER_HOST', "0.0.0.0")
TRACER_PORT = os.environ.get('TRACER_PORT', 4317)
TRACER_URL = f"http://{TRACER_HOST}:{TRACER_PORT}"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'api_gateway.middleware.TraceRequestMiddleware',
]

set_tracing_flag(bool(TRACING_ENABLED))

if TRACING_ENABLED:
    MIDDLEWARE.append('api_gateway.middleware.TraceMiddleware')

ROOT_URLCONF = 'main.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'main.wsgi.application'
ASGI_APPLICATION = 'main.asgi.application'

LOGS_DIR = os.path.join(BASE_DIR, 'logs')
os.makedirs(LOGS_DIR, exist_ok=True)
LOG_LEVEL = 'INFO' if DEBUG else 'ERROR'  # only log errors in production
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} [{module} {funcName} {lineno}] {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        }
    },
    'handlers': {
        'file': {
            'level': 'WARNING',
            'class': 'logging.FileHandler',
            'filename': LOGS_DIR + '/django.log',
            'formatter': 'verbose'
        },
        'console': {
            'level': LOG_LEVEL,
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
    },
    'loggers': {
        '': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True
        },
    }
}

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB', 'platform_db'),
        'USER': os.environ.get('POSTGRES_USER', 'platform_user'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'zaq11qaz'),
        'HOST': os.environ.get('POSTGRES_HOST', 'localhost'),
        'PORT': os.environ.get('POSTGRES_PORT', '5432'),
        'CONN_MAX_AGE': int(os.environ.get('WORKER_DB_CONNECTION_MAX_AGE', '900')),
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'user_domain.password_validation.MaximumLengthValidator',
        'OPTIONS': {
            'max_length': 150,
        }
    }
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.AllowAllUsersModelBackend'
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, 'storage/static/')
STATIC_URL = '/storage/static/'

DEFAULT_OFFLINE_TIMEOUT = int(os.environ.get('DEFAULT_OFFLINE_TIMEOUT', 43200))  # seconds

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Agents Links
AGENT_DOWNLOAD_URL_V1 = {
    'linux_x64': os.environ.get(
        'AGENT_DOWNLOAD_URL_V1_LINUX_X64'),
    'windows_x64': os.environ.get(
        'AGENT_DOWNLOAD_URL_V1_WINDOWS_x64')
}

AGENT_DOWNLOAD_URL_V2 = {
    'linux_x64': os.environ.get(
        'AGENT_DOWNLOAD_URL_V2_LINUX_X64'),
    'windows_x64': os.environ.get(
        'AGENT_DOWNLOAD_URL_V2_WINDOWS_x64')
}

LICENSE_SERVER_URL = os.environ.get('LICENSE_SERVER_URL', 'http://localhost')
LICENSING_PRODUCT_NAME = os.environ.get('LICENSING_PRODUCT_NAME', '')

DEFAULT_TEMPLATE_VERSION = os.environ.get('DEFAULT_TEMPLATE_VERSION')
DEFAULT_FAR_THRESHOLD_VALUE = os.environ.get('DEFAULT_FAR_THRESHOLD_VALUE', 1e-6)
DEFAULT_SCORE_THRESHOLD_VALUE = os.environ.get('DEFAULT_SCORE_THRESHOLD_VALUE', 0.85)

# thresholds were selected by eye: https://www.desmos.com/calculator/kp9rifevzx
BEST_QUALITY_THRESHOLD = float(os.environ.get('BEST_QUALITY_THRESHOLD', -750.))
PASS_QUALITY_THRESHOLD = float(os.environ.get('PASS_QUALITY_THRESHOLD', -900.))

CREATE_PROFILE_QUALITY_THRESHOLD = float(os.environ.get('CREATE_PROFILE_QUALITY_THRESHOLD', 0.5))

MATCHER_SERVICE_HOST = os.environ.get('MATCHER_SERVICE_HOST', 'localhost')
MATCHER_SERVICE_PORT = os.environ.get('MATCHER_SERVICE_PORT', 5001)
MATCHER_SERVICE_URL = f"http://{MATCHER_SERVICE_HOST}:{MATCHER_SERVICE_PORT}"

ACTIVITY_MATCHER_SERVICE_HOST = os.environ.get('ACTIVITY_MATCHER_SERVICE_HOST', 'localhost')
ACTIVITY_MATCHER_SERVICE_PORT = os.environ.get('ACTIVITY_MATCHER_SERVICE_PORT', 5002)
ACTIVITY_MATCHER_SERVICE_URL = f"http://{ACTIVITY_MATCHER_SERVICE_HOST}:{ACTIVITY_MATCHER_SERVICE_PORT}"

CAPTURER_NAME = os.environ.get('CAPTURER_NAME', "")

LIVENESS_SERVICE_PROVIDER = os.environ.get('LIVENESS_SERVICE_PROVIDER')

SERVICE_KEY = os.environ.get("SERVICE_KEY", "1q2w3e4r")

# QA group
QA_GROUP = 'QA'
STANDALONE_GROUP = 'standalone'
TS_GROUP = 'test_clock'
DEFAULT_QA_USER = os.environ.get('DEFAULT_QA_USER', 'test@mail.com')
DEFAULT_QA_PASSWORD = os.environ.get('DEFAULT_QA_PASSWORD', 'zaq11qaz')

BROKER_USER = os.environ.get('BROKER_USER', 'admin')
BROKER_PASSWORD = os.environ.get('BROKER_PASSWORD', 'zaq11qaz')
BROKER_HOST = os.environ.get('BROKER_HOST', 'localhost')
BROKER_PORT = int(os.environ.get('BROKER_PORT', 5672))
RABBIT_ADMIN_PORT = int(os.environ.get('RABBIT_ADMIN_PORT', 15672))

BROKER_URL = f"amqp://{BROKER_USER}:{BROKER_PASSWORD}@{BROKER_HOST}:{BROKER_PORT}"

CELERY_BROKER_URL = BROKER_URL

CACHE_HOST = os.environ.get('CACHE_SERVICE', 'localhost')
CACHE_PORT = os.environ.get('CACHE_PORT', '11211')

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
        'LOCATION': f'{CACHE_HOST}:{CACHE_PORT}',
    }
}

REDIS_HOST = os.environ.get('REDIS_HOST', '127.0.0.1')
REDIS_PORT = os.environ.get('REDIS_PORT', 6379)

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [(REDIS_HOST, REDIS_PORT)],
        },
    },
}

AGENT_INACTIVE_PERIOD_SECONDS = 60

DEFAULT_PROFILE_LABEL_TITLES = ['Staff', 'VIP', 'Shoplifter']

DATA_UPLOAD_MAX_MEMORY_SIZE = 8388608  # 8 Mb
MAX_IMAGE_WIDTH = int(os.environ.get('MAX_IMAGE_WIDTH', 4032))
MAX_IMAGE_HEIGHT = int(os.environ.get('MAX_IMAGE_HEIGHT', 4032))

# CELERY
AGENT_STATUS_CHECK_PERIOD = int(os.environ.get('AGENT_STATUS_CHECK_PERIOD', 30))
ACTIVITY_STATUS_CHECK_PERIOD = int(os.environ.get('ACTIVITY_STATUS_CHECK_PERIOD', 30))
INDEX_UPDATE_PERIOD = int(os.environ.get('INDEX_UPDATE_PERIOD', 60))
SAMPLE_RETENTION_CRON = os.environ.get('SAMPLE_RETENTION_CRON', "0 12 * * 0")

AGENT_EVENTS_QUEUE = os.environ.get('AGENT_EVENTS_QUEUE')
LICENSING_EVENTS_QUEUE = os.environ.get('LICENSING_EVENTS_QUEUE')
SERVICE_QUEUE = os.environ.get('SERVICE_QUEUE')
RETENTION_POLICY_QUEUE = os.environ.get('RETENTION_POLICY_QUEUE')
ACTIVITY_EVENTS_QUEUE = os.environ.get('ACTIVITY_EVENTS_QUEUE')
ACTIVITY_MATCHER_EVENTS_QUEUE = os.environ.get('ACTIVITY_MATCHER_EVENTS_QUEUE')
MATCHER_SCHEDULE_EVENTS_QUEUE = os.environ.get('MATCHER_SCHEDULE_EVENTS_QUEUE')
DEFERRED_PROFILE_DELETION = os.environ.get('DEFERRED_PROFILE_DELETION')
DEFERRED_REMOVE_PROFILES_FROM_GROUPS_QUEUE = os.environ.get('DEFERRED_REMOVE_PROFILES_FROM_GROUPS_QUEUE')
DEFERRED_REMOVE_PROFILES_FIELD_QUEUE = os.environ.get('DEFERRED_REMOVE_PROFILES_FIELD_QUEUE')
CREATE_DEFERRED_REMOVE_TASKS_QUEUE = os.environ.get('CREATE_DEFERRED_REMOVE_TASKS_QUEUE')

MATCHER_CALL_QUEUE = os.environ.get('MATCHER_CALL_QUEUE')
PLATFORM_MATCHER_EXCHANGE_NAME = os.environ.get("PLATFORM_MATCHER_EXCHANGE_NAME", "platform-matcher-exchange")

IS_ON_PREMISE = bool(int(os.environ['IS_ON_PREMISE']))

if not IS_ON_PREMISE:
    AUTHENTICATION_BACKENDS.append('api_gateway.auth_backends.LicenseServerAuth')

# Pluggable features
ENABLE_PROFILE_AUTOGENERATION = bool(os.environ.get('ENABLE_PROFILE_AUTOGENERATION'))

RESET_PASSWORD_URL = f'{BASE_SITE_URL}/password-recovery/new/?userId={{user_id}}&confirmationToken=' \
                     f'{{confirmation_token}}'
CONFIRM_URL = f'{BASE_SITE_URL}/email-confirm/success/?userId={{user_id}}&confirmationToken={{confirmation_token}}'

EMAIL_FROM = os.environ.get('EMAIL_FROM')
EMAIL_HOST = os.environ.get('EMAIL_HOST')
EMAIL_PORT = os.environ.get('EMAIL_PORT', 1025)
EMAIL_PORT = int(EMAIL_PORT) if EMAIL_PORT else EMAIL_PORT
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
EMAIL_PRODUCT_NAME = os.environ.get('CONTACT_PRODUCT_NAME')

EMAIL_USE_SSL = resolve_strange_bool('EMAIL_USE_SSL')
EMAIL_USE_TLS = resolve_strange_bool('EMAIL_USE_TLS')

EMAIL_CONTEXT = {
    'company_domain': os.environ.get('COMPANY_DOMAIN'),
    'company_short_name': os.environ.get('COMPANY_SHORT_NAME'),
    'company_full_name': os.environ.get('COMPANY_FULL_NAME'),
    'company_praise': os.environ.get('EMAIL_COMPANY_PRAISE'),
    'company_address': os.environ.get('EMAIL_COMPANY_ADDRESS'),
    'company_logo_path': os.environ.get('EMAIL_LOGO_PATH'),
    'current_year': str(datetime.now(pytz.UTC).year),
    'mail_to': quote(os.environ.get('EMAIL_MAIL_TO', 'support@example.com')),
    'team_name': os.environ.get('CONTACT_NAME'),
    'facebook_url': os.environ.get('EMAIL_FACEBOOK_URL'),
    'twitter_url': os.environ.get('EMAIL_TWITTER_URL'),
    'linkedin_url': os.environ.get('EMAIL_LINKEDIN_URL'),
    'instagram_url': os.environ.get('EMAIL_INSTAGRAM_URL'),
    'youtube_url': os.environ.get('EMAIL_YOUTUBE_URL'),
}

HTTP_REQUEST_TIMEOUT = int(os.environ.get('HTTP_REQUEST_TIMEOUT', 30))

WORKSPACE_CLEANING_DELTA = os.environ.get('WORKSPACE_CLEANING_DELTA')

WORKSPACE_CLEANING_DELTA = timedelta(seconds=int(WORKSPACE_CLEANING_DELTA)) if \
    WORKSPACE_CLEANING_DELTA else relativedelta(months=1)

# Default values
ACTIVITY_TTL = None
if os.environ.get('ACTIVITY_TTL'):
    ACTIVITY_TTL = int(os.environ.get('ACTIVITY_TTL'))
RETENTION_ACTIVITIES_COUNT = int(os.environ.get('RETENTION_ACTIVITIES_COUNT', 1000))
ACTIVITY_HANDLER_PERIOD = int(os.environ.get('ACTIVITY_HANDLER_PERIOD', 604800))  # in seconds
SAMPLE_TTL = int(os.environ.get('SAMPLE_TTL', 2592000))  # in seconds
QUERY_LIMIT = int(os.environ.get('QUERY_LIMIT', 100))
ACTIVITY_FAILED_TIME = int(os.environ.get('ACTIVITY_FAILED_TIME', 30))
DELETE_BATCH_SIZE = int(os.environ.get('DELETE_BATCH_SIZE', 100))
DELETE_SAMPLE_BATCH_SIZE = int(os.environ.get('DELETE_SAMPLE_BATCH_SIZE', 1000))

__default_req_timeout = 10
PROFILE_MATCHER_SERVICE_TIMEOUT = int(os.environ.get('PROFILE_MATCHER_SERVICE_TIMEOUT', __default_req_timeout))
ACTIVITY_MATCHER_SERVICE_TIMEOUT = int(os.environ.get('ACTIVITY_MATCHER_SERVICE_TIMEOUT', __default_req_timeout))


# Custom fields
if REQUIRED_PROFILE_FIELDS := os.environ.get('REQUIRED_PROFILE_FIELDS', []):
    REQUIRED_PROFILE_FIELDS = REQUIRED_PROFILE_FIELDS.split(',')

if REQUIRED_CAMERA_FIELDS := os.environ.get('REQUIRED_CAMERA_FIELDS', []):
    REQUIRED_CAMERA_FIELDS = REQUIRED_CAMERA_FIELDS.split(',')

# JWT
JWT_DECODE_SECRET = os.environ.get('JWT_DECODE_SECRET', 'zaq11qaz')
JWT_ENCODE_SECRET = os.environ.get('JWT_ENCODE_SECRET', 'zaq11qaz')
JWT_ALGORITHM = os.environ.get('JWT_ALGORITHM', 'HS256')
JWT_SVC_NAME = os.environ.get('JWT_SVC_NAME', 'monolith-svc')

# Other params
DISABLE_WORKSPACE_SEARCH_INDEX = json.loads(os.environ.get('DISABLE_WORKSPACE_SEARCH_INDEX', 'false').lower())
CALCULATED_ATTRIBUTES = os.environ.get('CALCULATED_ATTRIBUTES', '').split(',')
SERVICE_NAME = os.environ.get("SERVICE_NAME", "platform-backend")
MAX_RMQ_CONNECTION = int(os.environ.get("MAX_RMQ_CONNECTION", 1))
RPC_TIMEOUT = int(os.environ.get("RPC_TIMEOUT", 5))
ENABLE_AGENT = json.loads(os.environ.get('ENABLE_AGENT', 'true').lower())

CACHE_TTL = int(os.environ.get("CACHE_TTL", "60"))
CACHE_JITTER = int(os.environ.get("CACHE_JITTER", "10"))
CACHE_MAXSIZE = int(os.environ.get("CACHE_MAXSIZE", "1000"))
