# Generated by Django 3.2.20 on 2026-09-08 05:54

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_domain', '0001_initial'),
        ('label_domain', '0001_initial'),
        ('user_domain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('info', models.JSONField(default=dict, help_text="Person's info")),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('samples', models.ManyToManyField(blank=True, related_name='persons', to='data_domain.Sample')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='user_domain.workspace')),
            ],
            options={
                'verbose_name_plural': 'Persons',
                'db_table': 'person_domain_person',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('info', models.JSONField(default=dict, help_text="Profile's info")),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('person', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='person_domain.person')),
            ],
            options={
                'verbose_name_plural': 'Profiles',
                'db_table': 'person_domain_profile',
            },
        ),
        migrations.CreateModel(
            name='ProfileSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('workspace_id', models.UUIDField(editable=False)),
                ('extra_fields', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), default=list, size=None)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'ProfileSettings',
                'db_table': 'profile_settings',
            },
        ),
        migrations.CreateModel(
            name='ProfileGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_to_profile', to='label_domain.label')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_to_label', to='person_domain.profile')),
            ],
            options={
                'unique_together': {('profile', 'label')},
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_groups',
            field=models.ManyToManyField(related_name='profiles', through='person_domain.ProfileGroup', to='label_domain.Label'),
        ),
        migrations.AddField(
            model_name='profile',
            name='samples',
            field=models.ManyToManyField(blank=True, related_name='profile', to='data_domain.Sample'),
        ),
        migrations.AddField(
            model_name='profile',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='user_domain.workspace'),
        ),
    ]
