# Generated by Django 3.2.20 on 2026-09-08 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_key', models.CharField(max_length=255, unique=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'EmailTemplates',
                'db_table': 'user_domain_email_template',
            },
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(default='', help_text='Workspace title', max_length=100)),
                ('config', models.JSONField(db_index=True, default=dict, help_text='Workspace configuration. Include types of workspace')),
            ],
            options={
                'verbose_name_plural': 'Workspaces',
                'db_table': 'user_domain_workspace',
            },
        ),
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('permissions', models.CharField(choices=[('AD', 'Administrator'), ('VI', 'Viewer'), ('ED', 'Editor'), ('OW', 'Owner')], default='VI', max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='user_domain.workspace')),
            ],
            options={
                'verbose_name_plural': 'Accesses',
                'db_table': 'user_domain_access',
            },
        ),
        migrations.AddConstraint(
            model_name='access',
            constraint=models.UniqueConstraint(condition=models.Q(('permissions', 'OW')), fields=('workspace', 'permissions'), name='unique owner'),
        ),
    ]
