# Generated by Django 3.2.20 on 2026-09-08 05:54

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import platform_lib.utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('label_domain', '0001_initial'),
        ('user_domain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('info', models.JSONField(default=dict, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Agent',
                'db_table': 'collector_domain_agent',
            },
            bases=(models.Model, platform_lib.utils.ModelMixin),
        ),
        migrations.CreateModel(
            name='AgentIndexEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(max_length=30)),
                ('workspace_id', models.UUIDField()),
                ('profile_id', models.UUIDField()),
                ('person_id', models.UUIDField()),
                ('data', models.JSONField(default=dict)),
                ('creation_date', models.DateTimeField(default=platform_lib.utils.utcnow_with_tz)),
            ],
        ),
        migrations.CreateModel(
            name='AreaType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('info', models.JSONField(default=dict, help_text="Profile's info")),
                ('is_active', models.BooleanField(default=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='collector_domain.agent')),
            ],
            options={
                'verbose_name': 'Camera',
                'db_table': 'collector_domain_camera',
            },
            bases=(models.Model, platform_lib.utils.ModelMixin),
        ),
        migrations.CreateModel(
            name='CollectorSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('workspace_id', models.UUIDField(editable=False)),
                ('camera_fields', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), default=list, size=None)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'CollectorSettings',
                'db_table': 'collector_settings',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camera_location', to='collector_domain.camera')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camera_location', to='label_domain.label')),
            ],
        ),
        migrations.AddField(
            model_name='camera',
            name='locations',
            field=models.ManyToManyField(related_name='cameras', through='collector_domain.Location', to='label_domain.Label'),
        ),
        migrations.AddField(
            model_name='camera',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='user_domain.workspace'),
        ),
        migrations.CreateModel(
            name='AttentionArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('info', models.JSONField(default=dict, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('area_types', models.ManyToManyField(related_name='attention_areas', through='collector_domain.AreaType', to='label_domain.Label')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attention_areas', to='collector_domain.camera')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attention_areas', to='user_domain.workspace')),
            ],
            options={
                'verbose_name': 'Attention area',
                'db_table': 'collector_domain_attention_area',
            },
        ),
        migrations.AddField(
            model_name='areatype',
            name='attention_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_type', to='collector_domain.attentionarea'),
        ),
        migrations.AddField(
            model_name='areatype',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_type', to='label_domain.label'),
        ),
        migrations.AddIndex(
            model_name='agentindexevent',
            index=models.Index(fields=['creation_date'], name='collector_d_creatio_8bd586_idx'),
        ),
        migrations.AddField(
            model_name='agent',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='user_domain.workspace'),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('camera', 'label')},
        ),
        migrations.AlterUniqueTogether(
            name='areatype',
            unique_together={('attention_area', 'label')},
        ),
    ]
